CREATE TABLE "user" (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE token (
    id SERIAL PRIMARY KEY,
    value VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL,
    expiry INTEGER NOT NULL,
    user_id INTEGER NULL REFERENCES "user"(id) ON DELETE CASCADE
);

CREATE TABLE session (
    id SERIAL PRIMARY KEY,
    value VARCHAR(255) NOT NULL UNIQUE,
    expiry INTEGER NOT NULL,
    data TEXT NULL,
    user_id INTEGER REFERENCES "user"(id) ON DELETE CASCADE
);

CREATE TABLE item (
    id SERIAL PRIMARY KEY,
    text TEXT NOT NULL,
    deadline TIMESTAMP DEFAULT NULL,
    status VARCHAR(255) NOT NULL DEFAULT 'waiting',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_id INTEGER REFERENCES "user"(id) ON DELETE CASCADE
);
